const fs = require('fs');
const path = require('path');

// Extract the sha256 and logic from licenseManager to test
const SECRET_SALT = 'BADONE_MOTORS_MSH_BPL_2026_K9X7';

function sha256(ascii) {
  function rightRotate(value, amount) {
    return (value >>> amount) | (value << (32 - amount));
  }
  const mathPow = Math.pow;
  const maxWord = 0xffffffff;
  const h = [];
  const r = [];
  let primeCounter = 0;
  const isPrime = (n) => {
    for (let f = 2; f <= Math.sqrt(n); f++) if (n % f === 0) return false;
    return true;
  };
  while (primeCounter < 64) {
    if (isPrime(primeCounter + 2)) {
      if (h.length < 8) h.push((mathPow(primeCounter + 2, 0.5) * 0x100000000) | 0);
      r.push((mathPow(primeCounter + 2, 1 / 3) * 0x100000000) | 0);
      primeCounter++;
    }
    primeCounter++;
  }
  let words = [];
  let asciiLength = ascii.length * 8;
  ascii += String.fromCharCode(0x80);
  while ((ascii.length % 64) - 56) ascii += String.fromCharCode(0);
  for (let i = 0; i < ascii.length; i++) {
    const c = ascii.charCodeAt(i);
    if (c > 255) return null;
    words[(i >> 2)] |= c << (24 - (i % 4) * 8);
  }
  words[words.length] = (asciiLength / 0x100000000) | 0;
  words[words.length] = asciiLength | 0;
  for (let j = 0; j < words.length; j += 16) {
    const w = words.slice(j, j + 16);
    const oldHash = h.slice(0);
    for (let i = 0; i < 64; i++) {
      if (i >= 16) {
        const s0 = rightRotate(w[i-15],7)^rightRotate(w[i-15],18)^(w[i-15]>>>3);
        const s1 = rightRotate(w[i-2],17)^rightRotate(w[i-2],19)^(w[i-2]>>>10);
        w[i] = (w[i-16]+s0+w[i-7]+s1)|0;
      }
      const ch  = (h[4]&h[5])^(~h[4]&h[6]);
      const maj = (h[0]&h[1])^(h[0]&h[2])^(h[1]&h[2]);
      const t1  = (h[7]+(rightRotate(h[4],6)^rightRotate(h[4],11)^rightRotate(h[4],25))+ch+r[i]+w[i])|0;
      const t2  = ((rightRotate(h[0],2)^rightRotate(h[0],13)^rightRotate(h[0],22))+maj)|0;
      h[7]=h[6]; h[6]=h[5]; h[5]=h[4]; h[4]=(h[3]+t1)|0;
      h[3]=h[2]; h[2]=h[1]; h[1]=h[0]; h[0]=(t1+t2)|0;
    }
    for (let i = 0; i < 8; i++) h[i]=(h[i]+oldHash[i])|0;
  }
  let result = '';
  for (let i = 0; i < 8; i++) {
    let word = h[i];
    if (word < 0) word += maxWord + 1;
    let hex = word.toString(16);
    while (hex.length < 8) hex = '0' + hex;
    result += hex;
  }
  return result;
}

const mockDeviceHash = sha256("badone_msh_v2_android_samsung_galaxy_12345_motors");
console.log("1. Simulated Device Hash:", mockDeviceHash);

const shortIdRaw = mockDeviceHash.substring(0, 8).toUpperCase();
const displayId = shortIdRaw.substring(0, 4) + '-' + shortIdRaw.substring(4, 8);
console.log("2. Device ID shown on user app:", displayId);

// Admin generation
const raw = displayId.replace(/-/g, '').toUpperCase();
const adminHash = sha256(raw + SECRET_SALT);
const part1 = adminHash.substring(0, 4).toUpperCase();
const part2 = adminHash.substring(4, 8).toUpperCase();
const adminGeneratedCode = `MSH-${part1}-${part2}`;
console.log("3. Code generated by Admin HTML:", adminGeneratedCode);

// App validation
const appHash = sha256(raw + SECRET_SALT);
const appPart1 = appHash.substring(0, 4).toUpperCase();
const appPart2 = appHash.substring(4, 8).toUpperCase();
const expectedCode = `MSH-${appPart1}-${appPart2}`;
console.log("4. Code expected by App local check:", expectedCode);

if (adminGeneratedCode === expectedCode) {
    console.log("✅ SUCCESS: The offline activation algorithm perfectly matches.");
} else {
    console.log("❌ ERROR: Mismatch in offline activation algorithm.");
}
